// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // DIRECT_URL for migrations (bypasses Supabase PgBouncer pooler)
    // DATABASE_URL (pooled) is used at runtime via PrismaClient adapter
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
